language: node_js
script: travis_retry npm test
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_install:
  - 'npm install -g npm@latest'
after_success:
  - '[ -z "$COVERALLS_REPO_TOKEN" ] && tap --coverage-report=text-lcov | ./node_modules/.bin/coveralls'